# Generated by Django 5.1.5 on 2025-02-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'User'), ('Администратор', 'Admin')], default='Пользователь', help_text='Выберите роль пользователя', max_length=25, verbose_name='Роль пользователя'),
        ),
    ]
